version: '3'  # Use the latest version of Docker Compose

services:
  database:
    image: 'postgres:latest'  
    restart: 'always'
    
    environment:
      POSTGRES_USER: myuser  
      POSTGRES_PASSWORD: mypassword  
      POSTGRES_DB: mydatabase  
    ports:
      - '5432:5432'  
